### ISSUE TITLE
Task: Create a v1.0 release

### ISSUE THREAD

**Issue by ReinderVosDeWael** [cmi-dair/template-python-repository#83]
### Description

To discuss:

- Do we want to release via tag or via version branch? Tag is the easier method to implement; branch makes it easier to hotfix a critical bug in an already released version. Given the simplicity of this repository, and the fact I'd always recommend people use the most recent version, I'd be happy sticking to a tag system and accepting the additional risk. 
- Do we want to include the release action with the template? My instinct is no as I suspect this may be too specific to easily template across the wide variety of use-cases that this template repository allows for. 

### Tasks

- [x] Add a release action
  - [x] To discuss: delete release action in `setup_template.py`
- [x] Create a release v1.0.
- [x] Make a Zenodo DOI.
- [x] Add Zenodo DOI to the repository description.
- [x] Modify the stability badge to "stable".
- [ ] Tweet about it.
  - [ ] Eternal glory & fame.

**Comment by nx10** [comment]
> - Do we want to release via tag or via version branch? 

Let's do Tag 

> - Do we want to include the release action with the template?

How could we avoid that? Second repo that pulls this one and releases it?

**Comment by ReinderVosDeWael** [comment]
> > * Do we want to include the release action with the template?
> 
> How could we avoid that? Second repo that pulls this one and releases it?

Delete it in `setup_template.py`

**Comment by nx10** [comment]
We should make sure nothing bad happens when people commit before running the setup, maybe the release pipeline could fail if the name is not cmi-dair/template-python-repo

**Comment by nx10** [comment]
But in general that raises an interesting point, a collection of CI templates for releasing on pypi, zenodo, etc on tag would be nice

**Comment by ReinderVosDeWael** [comment]
We could stick to a manual release for now and think about how we want to handle this later
