### ISSUE TITLE
[after 1.0] Task: Add collection of compatible release CI actions for e.g. Pypi, Zenodo, ...

### ISSUE THREAD

**Issue by nx10** [cmi-dair/template-python-repository#85]
### Description

After the initial development period we want most of our packages released on pypi and possibly zenodo. Add compatible GitHub actions to this repo that can get copied / enabled manually at a later point in the development cycle.

### Tasks

- [ ] Add Pypi release action template (disabled by default)
- [ ] (Optional) Add zenodo release action template (disabled by default)
- [ ] (Optional) Other package repositories (anaconda)

**Comment by ReinderVosDeWael** [comment]
I'd have this depend on #87 - it'd be trivial to have the desired actions as a user prompt in a setup script.

**Comment by nx10** [comment]
https://github.com/cmi-dair/tsconcat/blob/main/.github/workflows/publish-pypi.yaml

For reference

**Comment by kaitj** [comment]
Adding to the list ofuseful release workflows, would also be good to have optional docker image build (that pushes to either dockerhub or ghcr).

Have one as reference that loosely combines aspects of @nx10's trigger above, @ReinderVosDeWael's [Brainspace CLI runner](https://github.com/childmindresearch/ba-timeseries-gradients) and a [previous workflow](https://github.com/khanlab/actions/blob/main/.github/workflows/workflow-release_task-deployDocker.yml) I've used:

https://github.com/childmindresearch/niftyone/blob/dockerfile/.github/workflows/deploy_container.yaml
